### ISSUE TITLE
Could not resolve com.github.rodm:gradle-teamcity-plugin:1.0

### ISSUE THREAD

**Issue by gaurav1264** [rodm/gradle-teamcity-plugin#26]
I am getting below error when using gradle teamcity plugin.

`Could not resolve com.github.rodm:gradle-teamcity-plugin:1.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/rodm/gradle-teamcity-plugin/1.0/gradle-teamcity-plugin-1.0.pom'`

When I looked at https://plugins.gradle.org/m2/com/github/rodm in browser, I get 'The requested path was not found.' error.

**My build configuration is below:**

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.github.rodm:gradle-teamcity-plugin:1.0"
    }
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'com.github.rodm.teamcity-server'  //Server-side plugin essentials
apply plugin: 'com.github.rodm.teamcity-common'  //To get teamcity openAPI jars

teamcity {
    // Use TeamCity 10.0 API
    version = '10.0'
    server {
        // Locate the plugin descriptor in the root directory of the project
        descriptor = file('teamcity-plugin.xml')
        tokens = [VERSION: project.version, VENDOR_NAME: 'test.com']
    }
}

Looks like the plugin is not published in jcenter repository.

**Comment by rodm** [comment]
Have you tried to build your plugin since raising this issue? 

I've cleaned out my Gradle cache and built the following 2 projects that use the plugin, [Gradle Build Cache](https://github.com/rodm/teamcity-gradle-build-cache-plugin) and [Gradle Init Scripts](https://github.com/rodm/teamcity-gradle-init-scripts-plugin) without a problem.

It could have been a temporary problem with the Gradle plugin repository or do you have a proxy, if so you may need to configure Gradle to with the proxy settings.
